version: '2.1'
services:

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root

  mongo:
    image: mongo:latest
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    ports:
      - 6379:6379
